/**
 * Defines the possible time granularities for reporting data aggregation.
 */
export type Granularity = 'day' | 'week' | 'month' | 'quarter' | 'year';

/**
 * Represents a single data point in a time-series analysis of sales.
 */
export interface SalesBucket {
  /** The starting date or label for the period (e.g., '2023-10-26'). */
  period: string;
  /** The total revenue generated within this period. */
  total: number;
  /** The total number of transactions within this period. */
  transactions: number;
  /** A breakdown of sales by payment method within this period. */
  paymentMethods: Record<string, { count: number; total: number }>;
}

/**
 * Represents the performance metrics for a single employee over a given period.
 */
export interface EmployeePerformanceRow {
  /** The unique identifier for the employee. */
  employeeId: string;
  /** The total revenue generated by the employee. */
  revenue: number;
  /** The total number of tickets (sales) handled by the employee. */
  tickets: number;
  /** The average basket value for sales handled by the employee. */
  avgBasket: number;
}

/**
 * Represents the performance metrics for a single product category.
 */
export interface CategoryPerformanceRow {
  /** The name of the product category. */
  category: string;
  /** The total revenue generated from this category. */
  revenue: number;
  /** The total number of distinct units sold from this category. */
  units: number;
  /** The total number of items sold from this category. */
  items: number;
  /** The percentage of total revenue that this category accounts for. */
  shareOfRevenue: number;
}

/**
 * Represents an overview of a single product batch with an upcoming expiration date.
 */
export interface ExpiryOverviewRow {
  /** The unique identifier for the batch. */
  batchId: number;
  /** The lot number of the batch, if available. */
  lotNumber?: string | null;
  /** Basic information about the product. */
  product: { id: number; name: string; sku?: string | null };
  /** The storage location of the batch, if available. */
  storageLocation?: { id: number; code?: string | null } | null;
  /** The expiration date of the batch. */
  expirationDate?: string | null;
  /** The remaining quantity of items in the batch. */
  quantity: number;
  /** The number of days remaining until the batch expires. */
  daysRemaining: number | null;
  /** The current status of the batch (e.g., 'EXPIRING_SOON'). */
  status: string;
}

/**
 * Defines the structure of the API response for the main reporting dashboard.
 */
export interface DashboardResponse {
  /** Time-series data for sales performance. */
  sales: SalesBucket[];
  /** Performance metrics for top employees. */
  employees: EmployeePerformanceRow[];
  /** Performance metrics for top product categories. */
  categories: CategoryPerformanceRow[];
  /** A list of product batches nearing their expiration date. */
  expiry: ExpiryOverviewRow[];
}

/**
 * Defines the available filters for querying reporting data.
 */
export interface ReportingFilters {
  /** The start date for the reporting period (YYYY-MM-DD). */
  startDate?: string;
  /** The end date for the reporting period (YYYY-MM-DD). */
  endDate?: string;
  /** The time granularity for data aggregation. */
  granularity?: Granularity;
  /** The specific location ID to filter by. */
  locationId?: string;
}

/**
 * Defines the types of reports that can be generated and exported.
 */
export type ReportExportType =
  | 'SALES_SUMMARY'
  | 'EMPLOYEE_PERFORMANCE'
  | 'CATEGORY_PERFORMANCE';

/**
 * Defines the available file formats for report exports.
 */
export type ReportExportFormat = 'CSV' | 'XLSX';

/**
 * Defines the possible statuses of a report export job.
 */
export type ReportExportStatus = 'PENDING' | 'PROCESSING' | 'READY' | 'FAILED';

/**
 * Defines the filters that were applied to a specific report export.
 */
export interface ReportExportFilters {
  startDate?: string;
  endDate?: string;
  granularity?: string;
  locationId?: string;
}

/**
 * Represents a summary of a single report export job.
 */
export interface ReportExportSummary {
  /** The unique identifier for the export job. */
  id: number;
  /** The type of the report that was exported. */
  type: ReportExportType;
  /** The file format of the export. */
  format: ReportExportFormat;
  /** The current status of the export job. */
  status: ReportExportStatus;
  /** The timestamp when the export job was created. */
  createdAt: string;
  /** The timestamp when the export job started processing. */
  startedAt?: string | null;
  /** The timestamp when the export job was completed. */
  completedAt?: string | null;
  /** The name of the generated file. */
  fileName?: string | null;
  /** The MIME type of the generated file. */
  mimeType?: string | null;
  /** The path to download the generated file. */
  downloadPath?: string | null;
  /** The filters that were applied to this export. */
  filters: ReportExportFilters;
  /** The email address to notify upon completion, if provided. */
  notificationEmail?: string | null;
  /** Any error message if the job failed. */
  error?: string | null;
}

/**
 * Defines the payload for requesting a new report export.
 */
export interface ReportExportRequestPayload extends ReportingFilters {
  /** The type of report to generate. */
  type: ReportExportType;
  /** The desired file format for the report. */
  format: ReportExportFormat;
  /** An optional email address to notify when the export is ready. */
  notificationEmail?: string;
}

/**
 * Represents a location that can be used for filtering reports.
 */
export interface LocationOption {
  /** The unique identifier for the location. */
  id: string;
  /** The human-readable label for the location. */
  label: string;
}
